---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u3125820/public_html/
    - ./bin/hugo --minify
    - rsync -az public/* $DEPLOYPATH --delete
    - rm -rf public/
    - git push -u origin --all